using System.Collections.Generic;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Robust.Client.UserInterface.Controls.OptionButton;

namespace Content.Client.Sandbox
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public partial class ExplosionSpawnWindow : SS14Window
    {
        [Dependency] private readonly IClientConsoleHost _conHost = default!;
        [Dependency] private readonly IMapManager _mapManager = default!;
        [Dependency] private readonly IPlayerManager _playerManager = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;

        private List<GridId> _gridData = new();
        private bool _preview;

        public ExplosionSpawnWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            GridOptions.OnItemSelected += GridSelected;
            Recentre.OnPressed += (_) => SetLocation();
            Directed.OnToggled += DirectedToggled;
            Preview.OnToggled += PreviewToggled;
            Spawn.OnPressed += SubmitButtonOnOnPressed;

            TileX.ValueChanged += (_, _) => UpdatePreview();
            TileY.ValueChanged += (_, _) => UpdatePreview();
            Intensity.OnValueChanged += (_) => UpdatePreview();
            Slope.OnValueChanged += (_) => UpdatePreview();
            MaxIntensity.OnValueChanged += (_) => UpdatePreview();
            Angle.OnValueChanged += (_) => UpdatePreview();
            Spread.OnValueChanged += (_) => UpdatePreview();
            Distance.OnValueChanged += (_) => UpdatePreview();
        }

        private void GridSelected(ItemSelectedEventArgs args)
        {
            GridOptions.SelectId(args.Id);
            UpdatePreview();
        }

        private void PreviewToggled(ButtonToggledEventArgs args)
        {
            _preview = Preview.Pressed;
            if (!_preview)
                _conHost.ExecuteCommand("explosion clear");
            else
                UpdatePreview();
        }

        private void DirectedToggled(ButtonToggledEventArgs args)
        {
            DirectedBox.Visible = Directed.Pressed;

            // Is there really no way to easily get auto-resizing windows!?
            if (DirectedBox.Visible)
                SetHeight = Height + DirectedBox.MaxHeight;
            else
                SetHeight = Height - DirectedBox.MaxHeight;

            UpdatePreview();
        }

        protected override void EnteredTree()
        {
            SetLocation();
        }

        private void UpdateGrids()
        {
            _gridData .Clear();
            GridOptions.Clear();
            foreach (var grid in _mapManager.GetAllGrids())
            {
                _gridData.Add(grid.Index);
                GridOptions.AddItem($"{grid.Index}");
            }

            // spaaaaaaace
            _gridData.Add(GridId.Invalid);
            GridOptions.AddItem($"{GridId.Invalid}"); 
        }

        /// <summary>
        ///     Set the current grid & indices based on the attached entities current location.
        /// </summary>
        private void SetLocation()
        {
            UpdateGrids();

            var transform = _playerManager.LocalPlayer?.ControlledEntity?.Transform;
            if (transform == null)
                return;

            // avoid a triple preview update when setting values
            _preview = false;

            GridOptions.Select(_gridData.IndexOf(transform.GridID));

            Vector2i tileIndices;
            if (_mapManager.TryGetGrid(transform.GridID, out var grid))
                tileIndices = grid.TileIndicesFor(transform.Coordinates);
            else
                tileIndices = transform.Coordinates.ToVector2i(_entityManager, _mapManager);

            TileX.Value = tileIndices.X;
            TileY.Value = tileIndices.Y;

            _preview = Preview.Pressed;
            UpdatePreview();
        }

        private void UpdatePreview()
        {
            if (_preview)
                _conHost.ExecuteCommand("explosion preview " + GetCommandArgs());
        }

        private string GetCommandArgs()
        {
            var gridId = _gridData[GridOptions.SelectedId];
            var cmd = $"{TileX.Value} {TileY.Value} {gridId} {Intensity.Value} {Slope.Value} {MaxIntensity.Value}";

            if (!Directed.Pressed)
                return cmd;

            cmd += $" {Angle.Value} {Spread.Value} {Distance.Value}";

            return cmd;
        }

        private void SubmitButtonOnOnPressed(ButtonEventArgs args)
        {
            // clear preview
            Preview.Pressed = false;
            _conHost.ExecuteCommand("explosion clear");

            _conHost.ExecuteCommand("explosion spawn " + GetCommandArgs());
        }
    }
}
