using System.Collections.Generic;
using System.Linq;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;

namespace Content.Client.Sandbox
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public partial class ExplosionSpawnWindow : SS14Window
    {
        // hot damn spinbox already provides InitDefaultButtons
        // basically +- buttons!

        public ExplosionSpawnWindow()
        {
            //MinSize = SetSize = (300, 200);
            RobustXamlLoader.Load(this);
        }

        /*private void OnStationEventsReceived()
        {
            // fill events dropdown
            _data = _eventManager.StationEvents.ToList();
            EventsOptions.Clear();
            foreach (var stationEvent in _data)
            {
                EventsOptions.AddItem(stationEvent);
            }
            EventsOptions.AddItem(Loc.GetString("station-events-window-random-text"));

            // Enable all UI elements
            EventsOptions.Disabled = false;
            PauseButton.Disabled = false;
            ResumeButton.Disabled = false;
            SubmitButton.Disabled = false;

            // Subscribe to UI events
            EventsOptions.OnItemSelected += eventArgs => EventsOptions.SelectId(eventArgs.Id);
            SubmitButton.OnPressed += SubmitButtonOnOnPressed;
        }*/

        /*private void SubmitButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
        {
            if (_data == null)
                return;

            // random is always last option
            var id = EventsOptions.SelectedId;
            var selectedEvent = id < _data.Count ? _data[id] : "random";

            IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand($"events run \"{selectedEvent}\"");
        }*/
    }
}
